dijkstra.exe: main.o hash.o heap.o graph.o
	g++ -o dijkstra.exe main.o hash.o heap.o graph.o
main.o: main.cpp
	g++ -c main.cpp
hash.o: hash.cpp hash.h
	g++ -c hash.cpp
heap.o: heap.cpp heap.h
	g++ -c heap.cpp
graph.o: graph.cpp graph.h
	g++ -c graph.cpp
